# Generated by Django 3.2.3 on 2021-11-22 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20211122_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activelisting',
            name='createdby',
        ),
        migrations.AddField(
            model_name='activelisting',
            name='upload_author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activelisting',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highest_bidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
