# Generated by Django 3.2.3 on 2021-11-22 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20211122_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelisting',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activelisting',
            name='upload_author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activelisting',
            name='categories',
            field=models.ForeignKey(default='General', on_delete=django.db.models.deletion.CASCADE, to='auctions.categories'),
        ),
    ]
