# Generated by Django 3.2.3 on 2021-11-27 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20211122_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelisting',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('cars/trucks', 'Cars/Trucks'), ('home furniture', 'Home Furniture'), ('electronics', 'Electronics'), ('garden', 'Garden'), ('animals', 'Animals')], max_length=17),
        ),
    ]
